#!/bin/bash
clear;
g++ main.cpp CompteBancaire/CompteBancaire.cpp CompteCourant/CompteCourant.cpp CompteJoint/CompteJoint.cpp CompteTerme/CompteTerme.cpp CompteEpargne/CompteEpargne.cpp CompteIndivis/CompteIndivis.cpp CompteTitre/CompteTitre.cpp -o prog;
echo "C'est Compilé :)";
echo "Exécution....";
sleep 5;
./prog;
